BEGIN NOT ATOMIC
INSERT INTO country (country_code, country) VALUES('AD', 'Andorra');
INSERT INTO country (country_code, country) VALUES('AE', 'United Arab Emirates');
INSERT INTO country (country_code, country) VALUES('AF', 'Afghanistan');
INSERT INTO country (country_code, country) VALUES('AG', 'Antigua and Barbuda');
INSERT INTO country (country_code, country) VALUES('AI', 'Anguilla');
INSERT INTO country (country_code, country) VALUES('AL', 'Albania');
INSERT INTO country (country_code, country) VALUES('AM', 'Armenia');
INSERT INTO country (country_code, country) VALUES('AN', 'Antilles');
INSERT INTO country (country_code, country) VALUES('AO', 'Angola');
INSERT INTO country (country_code, country) VALUES('AQ', 'Antarctica');
INSERT INTO country (country_code, country) VALUES('AR', 'Argentina');
INSERT INTO country (country_code, country) VALUES('AS', 'American Samoa');
INSERT INTO country (country_code, country) VALUES('AT', 'Austria');
INSERT INTO country (country_code, country) VALUES('AU', 'Australia');
INSERT INTO country (country_code, country) VALUES('AW', 'Aruba');
INSERT INTO country (country_code, country) VALUES('AZ', 'Azerbaijan');
INSERT INTO country (country_code, country) VALUES('BA', 'Bosnia Herzegovina');
INSERT INTO country (country_code, country) VALUES('BB', 'Barbados');
INSERT INTO country (country_code, country) VALUES('BD', 'Bangladesh');
INSERT INTO country (country_code, country) VALUES('BE', 'Belgium');
INSERT INTO country (country_code, country) VALUES('BF', 'Burkina Faso');
INSERT INTO country (country_code, country) VALUES('BG', 'Bulgaria');
INSERT INTO country (country_code, country) VALUES('BH', 'Bahrain');
INSERT INTO country (country_code, country) VALUES('BI', 'Burundi');
INSERT INTO country (country_code, country) VALUES('BJ', 'Benin');
INSERT INTO country (country_code, country) VALUES('BL', 'Saint Barthélemy');
INSERT INTO country (country_code, country) VALUES('BM', 'Bermuda');
INSERT INTO country (country_code, country) VALUES('BN', 'Brunei');
INSERT INTO country (country_code, country) VALUES('BO', 'Bolivia');
INSERT INTO country (country_code, country) VALUES('BQ', 'Bonaire');
INSERT INTO country (country_code, country) VALUES('BR', 'Brazil');
INSERT INTO country (country_code, country) VALUES('BS', 'Bahamas');
INSERT INTO country (country_code, country) VALUES('BT', 'Bhutan');
INSERT INTO country (country_code, country) VALUES('BW', 'Botswana');
INSERT INTO country (country_code, country) VALUES('BY', 'Belarus');
INSERT INTO country (country_code, country) VALUES('BZ', 'Belize');
INSERT INTO country (country_code, country) VALUES('CA', 'Canada');
INSERT INTO country (country_code, country) VALUES('CC', 'Cocos Isds');
INSERT INTO country (country_code, country) VALUES('CD', 'Congo');
INSERT INTO country (country_code, country) VALUES('CF', 'Central African Rep.');
INSERT INTO country (country_code, country) VALUES('CG', 'Congo');
INSERT INTO country (country_code, country) VALUES('CH', 'Switzerland');
INSERT INTO country (country_code, country) VALUES('CI', 'Côte d''Ivoire');
INSERT INTO country (country_code, country) VALUES('CK', 'Cook Isds');
INSERT INTO country (country_code, country) VALUES('CL', 'Chile');
INSERT INTO country (country_code, country) VALUES('CM', 'Cameroon');
INSERT INTO country (country_code, country) VALUES('CN', 'China');
INSERT INTO country (country_code, country) VALUES('CO', 'Colombia');
INSERT INTO country (country_code, country) VALUES('CR', 'Costa Rica');
INSERT INTO country (country_code, country) VALUES('CZ', 'Czechoslovakia');
INSERT INTO country (country_code, country) VALUES('CS', 'Serbia and Montenegro');
INSERT INTO country (country_code, country) VALUES('CU', 'Cuba');
INSERT INTO country (country_code, country) VALUES('CV', 'Cabo Verde');
INSERT INTO country (country_code, country) VALUES('CW', 'Curaçao');
INSERT INTO country (country_code, country) VALUES('CX', 'Christmas Isds');
INSERT INTO country (country_code, country) VALUES('CY', 'Cyprus');
INSERT INTO country (country_code, country) VALUES('DE', 'Germany');
INSERT INTO country (country_code, country) VALUES('DJ', 'Djibouti');
INSERT INTO country (country_code, country) VALUES('DK', 'Denmark');
INSERT INTO country (country_code, country) VALUES('DM', 'Dominica');
INSERT INTO country (country_code, country) VALUES('DO', 'Dominican Rep.');
INSERT INTO country (country_code, country) VALUES('DZ', 'Algeria');
INSERT INTO country (country_code, country) VALUES('EC', 'Ecuador');
INSERT INTO country (country_code, country) VALUES('EE', 'Estonia');
INSERT INTO country (country_code, country) VALUES('EG', 'Egypt');
INSERT INTO country (country_code, country) VALUES('EH', 'Western Sahara');
INSERT INTO country (country_code, country) VALUES('ER', 'Eritrea');
INSERT INTO country (country_code, country) VALUES('ES', 'Spain');
INSERT INTO country (country_code, country) VALUES('ET', 'Ethiopia');
INSERT INTO country (country_code, country) VALUES('EU', 'EU-28');
INSERT INTO country (country_code, country) VALUES('FI', 'Finland');
INSERT INTO country (country_code, country) VALUES('FJ', 'Fiji');
INSERT INTO country (country_code, country) VALUES('FK', 'Falkland Isds (Malvinas)');
INSERT INTO country (country_code, country) VALUES('FM', 'FS Micronesia');
INSERT INTO country (country_code, country) VALUES('FO', 'Faeroe Isds');
INSERT INTO country (country_code, country) VALUES('FQ', 'Fr. South Antarctic Terr.');
INSERT INTO country (country_code, country) VALUES('FR', 'France');
INSERT INTO country (country_code, country) VALUES('GA', 'Gabon');
INSERT INTO country (country_code, country) VALUES('GB', 'United Kingdom');
INSERT INTO country (country_code, country) VALUES('GD', 'Grenada');
INSERT INTO country (country_code, country) VALUES('GE', 'Georgia');
INSERT INTO country (country_code, country) VALUES('GF', 'French Guiana');
INSERT INTO country (country_code, country) VALUES('GH', 'Ghana');
INSERT INTO country (country_code, country) VALUES('GI', 'Gibraltar');
INSERT INTO country (country_code, country) VALUES('GL', 'Greenland');
INSERT INTO country (country_code, country) VALUES('GM', 'Gambia');
INSERT INTO country (country_code, country) VALUES('GN', 'Guinea');
INSERT INTO country (country_code, country) VALUES('GP', 'Guadeloupe');
INSERT INTO country (country_code, country) VALUES('GQ', 'Equatorial Guinea');
INSERT INTO country (country_code, country) VALUES('GR', 'Greece');
INSERT INTO country (country_code, country) VALUES('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country (country_code, country) VALUES('GT', 'Guatemala');
INSERT INTO country (country_code, country) VALUES('GU', 'Guam');
INSERT INTO country (country_code, country) VALUES('GW', 'Guinea-Bissau');
INSERT INTO country (country_code, country) VALUES('GY', 'Guyana');
INSERT INTO country (country_code, country) VALUES('HK', 'Hong Kong');
INSERT INTO country (country_code, country) VALUES('HM', 'Heard Island and McDonald Islands');
INSERT INTO country (country_code, country) VALUES('HN', 'Honduras');
INSERT INTO country (country_code, country) VALUES('HR', 'Croatia');
INSERT INTO country (country_code, country) VALUES('HT', 'Haiti');
INSERT INTO country (country_code, country) VALUES('HU', 'Hungary');
INSERT INTO country (country_code, country) VALUES('ID', 'Indonesia');
INSERT INTO country (country_code, country) VALUES('IE', 'Ireland');
INSERT INTO country (country_code, country) VALUES('IL', 'Israel');
INSERT INTO country (country_code, country) VALUES('IN', 'India');
INSERT INTO country (country_code, country) VALUES('IO', 'Br. Indian Ocean Terr.');
INSERT INTO country (country_code, country) VALUES('IQ', 'Iraq');
INSERT INTO country (country_code, country) VALUES('IR', 'Iran');
INSERT INTO country (country_code, country) VALUES('IS', 'Iceland');
INSERT INTO country (country_code, country) VALUES('IT', 'Italy');
INSERT INTO country (country_code, country) VALUES('JM', 'Jamaica');
INSERT INTO country (country_code, country) VALUES('JO', 'Jordan');
INSERT INTO country (country_code, country) VALUES('JP', 'Japan');
INSERT INTO country (country_code, country) VALUES('KE', 'Kenya');
INSERT INTO country (country_code, country) VALUES('KG', 'Kyrgyzstan');
INSERT INTO country (country_code, country) VALUES('KH', 'Cambodia');
INSERT INTO country (country_code, country) VALUES('KI', 'Kiribati');
INSERT INTO country (country_code, country) VALUES('KM', 'Comoros');
INSERT INTO country (country_code, country) VALUES('KN', 'Saint Kitts and Nevis');
INSERT INTO country (country_code, country) VALUES('KP', 'Dem. People''s Rep. of Korea');
INSERT INTO country (country_code, country) VALUES('KR', 'Rep. of Korea');
INSERT INTO country (country_code, country) VALUES('KW', 'Kuwait');
INSERT INTO country (country_code, country) VALUES('KY', 'Cayman Isds');
INSERT INTO country (country_code, country) VALUES('KZ', 'Kazakhstan');
INSERT INTO country (country_code, country) VALUES('LA', 'Lao People''s Dem. Rep.');
INSERT INTO country (country_code, country) VALUES('LB', 'Lebanon');
INSERT INTO country (country_code, country) VALUES('LC', 'Saint Lucia');
INSERT INTO country (country_code, country) VALUES('LK', 'Sri Lanka');
INSERT INTO country (country_code, country) VALUES('LR', 'Liberia');
INSERT INTO country (country_code, country) VALUES('LS', 'Lesotho');
INSERT INTO country (country_code, country) VALUES('LT', 'Lithuania');
INSERT INTO country (country_code, country) VALUES('LU', 'Luxembourg');
INSERT INTO country (country_code, country) VALUES('LV', 'Latvia');
INSERT INTO country (country_code, country) VALUES('LY', 'Libya');
INSERT INTO country (country_code, country) VALUES('MA', 'Morocco');
INSERT INTO country (country_code, country) VALUES('MD', 'Rep. of Moldova');
INSERT INTO country (country_code, country) VALUES('ME', 'Montenegro');
INSERT INTO country (country_code, country) VALUES('MG', 'Madagascar');
INSERT INTO country (country_code, country) VALUES('MH', 'Marshall Isds');
INSERT INTO country (country_code, country) VALUES('MK', 'TFYR of Macedonia');
INSERT INTO country (country_code, country) VALUES('ML', 'Mali');
INSERT INTO country (country_code, country) VALUES('MM', 'Myanmar');
INSERT INTO country (country_code, country) VALUES('MN', 'Mongolia');
INSERT INTO country (country_code, country) VALUES('MO', 'China, Macao SAR');
INSERT INTO country (country_code, country) VALUES('MP', 'N. Mariana Isds');
INSERT INTO country (country_code, country) VALUES('MQ', 'Martinique');
INSERT INTO country (country_code, country) VALUES('MR', 'Mauritania');
INSERT INTO country (country_code, country) VALUES('MS', 'Montserrat');
INSERT INTO country (country_code, country) VALUES('MT', 'Malta');
INSERT INTO country (country_code, country) VALUES('MU', 'Mauritius');
INSERT INTO country (country_code, country) VALUES('MV', 'Maldives');
INSERT INTO country (country_code, country) VALUES('MW', 'Malawi');
INSERT INTO country (country_code, country) VALUES('MX', 'Mexico');
INSERT INTO country (country_code, country) VALUES('MY', 'Malaysia');
INSERT INTO country (country_code, country) VALUES('MZ', 'Mozambique');
INSERT INTO country (country_code, country) VALUES('NA', 'Namibia');
INSERT INTO country (country_code, country) VALUES('NC', 'New Caledonia');
INSERT INTO country (country_code, country) VALUES('NE', 'Niger');
INSERT INTO country (country_code, country) VALUES('NF', 'Norfolk Isds');
INSERT INTO country (country_code, country) VALUES('NG', 'Nigeria');
INSERT INTO country (country_code, country) VALUES('NI', 'Nicaragua');
INSERT INTO country (country_code, country) VALUES('NL', 'Netherlands');
INSERT INTO country (country_code, country) VALUES('NO', 'Norway');
INSERT INTO country (country_code, country) VALUES('NP', 'Nepal');
INSERT INTO country (country_code, country) VALUES('NR', 'Nauru');
INSERT INTO country (country_code, country) VALUES('NU', 'Niue');
INSERT INTO country (country_code, country) VALUES('NZ', 'New Zealand');
INSERT INTO country (country_code, country) VALUES('OM', 'Oman');
INSERT INTO country (country_code, country) VALUES('PA', 'Panama');
INSERT INTO country (country_code, country) VALUES('PE', 'Peru');
INSERT INTO country (country_code, country) VALUES('PF', 'French Polynesia');
INSERT INTO country (country_code, country) VALUES('PG', 'Papua New Guinea');
INSERT INTO country (country_code, country) VALUES('PH', 'Philippines');
INSERT INTO country (country_code, country) VALUES('PK', 'Pakistan');
INSERT INTO country (country_code, country) VALUES('PL', 'Poland');
INSERT INTO country (country_code, country) VALUES('PM', 'Saint Pierre and Miquelon');
INSERT INTO country (country_code, country) VALUES('PN', 'Pitcairn');
INSERT INTO country (country_code, country) VALUES('PS', 'State of Palestine');
INSERT INTO country (country_code, country) VALUES('PT', 'Portugal');
INSERT INTO country (country_code, country) VALUES('PW', 'Palau');
INSERT INTO country (country_code, country) VALUES('PY', 'Paraguay');
INSERT INTO country (country_code, country) VALUES('QA', 'Qatar');
INSERT INTO country (country_code, country) VALUES('RE', 'Réunion');
INSERT INTO country (country_code, country) VALUES('RO', 'Romania');
INSERT INTO country (country_code, country) VALUES('RS', 'Serbia');
INSERT INTO country (country_code, country) VALUES('RU', 'Russian Federation');
INSERT INTO country (country_code, country) VALUES('RW', 'Rwanda');
INSERT INTO country (country_code, country) VALUES('SA', 'Saudi Arabia');
INSERT INTO country (country_code, country) VALUES('SB', 'Solomon Isds');
INSERT INTO country (country_code, country) VALUES('SC', 'Seychelles');
INSERT INTO country (country_code, country) VALUES('SD', 'Sudan');
INSERT INTO country (country_code, country) VALUES('SE', 'Sweden');
INSERT INTO country (country_code, country) VALUES('SG', 'Singapore');
INSERT INTO country (country_code, country) VALUES('SH', 'Saint Helena');
INSERT INTO country (country_code, country) VALUES('SI', 'Slovenia');
INSERT INTO country (country_code, country) VALUES('SK', 'Slovakia');
INSERT INTO country (country_code, country) VALUES('SL', 'Sierra Leone');
INSERT INTO country (country_code, country) VALUES('SM', 'San Marino');
INSERT INTO country (country_code, country) VALUES('SN', 'Senegal');
INSERT INTO country (country_code, country) VALUES('SO', 'Somalia');
INSERT INTO country (country_code, country) VALUES('SR', 'Suriname');
INSERT INTO country (country_code, country) VALUES('SS', 'South Sudan');
INSERT INTO country (country_code, country) VALUES('ST', 'Sao Tome and Principe');
INSERT INTO country (country_code, country) VALUES('SV', 'El Salvador');
INSERT INTO country (country_code, country) VALUES('SX', 'Saint Maarten');
INSERT INTO country (country_code, country) VALUES('SY', 'Syria');
INSERT INTO country (country_code, country) VALUES('SZ', 'Swaziland');
INSERT INTO country (country_code, country) VALUES('TC', 'Turks and Caicos Isds');
INSERT INTO country (country_code, country) VALUES('TD', 'Chad');
INSERT INTO country (country_code, country) VALUES('TG', 'Togo');
INSERT INTO country (country_code, country) VALUES('TH', 'Thailand');
INSERT INTO country (country_code, country) VALUES('TJ', 'Tajikistan');
INSERT INTO country (country_code, country) VALUES('TK', 'Tokelau');
INSERT INTO country (country_code, country) VALUES('TL', 'Timor-Leste');
INSERT INTO country (country_code, country) VALUES('TM', 'Turkmenistan');
INSERT INTO country (country_code, country) VALUES('TN', 'Tunisia');
INSERT INTO country (country_code, country) VALUES('TO', 'Tonga');
INSERT INTO country (country_code, country) VALUES('TR', 'Turkey');
INSERT INTO country (country_code, country) VALUES('TT', 'Trinidad and Tobago');
INSERT INTO country (country_code, country) VALUES('TV', 'Tuvalu');
INSERT INTO country (country_code, country) VALUES('TZ', 'United Rep. of Tanzania');
INSERT INTO country (country_code, country) VALUES('UA', 'Ukraine');
INSERT INTO country (country_code, country) VALUES('UG', 'Uganda');
INSERT INTO country (country_code, country) VALUES('UM', 'United States Minor Outlying Islands');
INSERT INTO country (country_code, country) VALUES('US', 'USA');
INSERT INTO country (country_code, country) VALUES('UY', 'Uruguay');
INSERT INTO country (country_code, country) VALUES('UZ', 'Uzbekistan');
INSERT INTO country (country_code, country) VALUES('VA', 'Holy See (Vatican City State)');
INSERT INTO country (country_code, country) VALUES('VC', 'Saint Vincent and the Grenadines');
INSERT INTO country (country_code, country) VALUES('VE', 'Venezuela');
INSERT INTO country (country_code, country) VALUES('VG', 'Br. Virgin Isds');
INSERT INTO country (country_code, country) VALUES('VI', 'US Virgin Isds');
INSERT INTO country (country_code, country) VALUES('VN', 'Vietnam');
INSERT INTO country (country_code, country) VALUES('VU', 'Vanuatu');
INSERT INTO country (country_code, country) VALUES('WF', 'Wallis and Futuna Isds');
INSERT INTO country (country_code, country) VALUES('WL', 'World');
INSERT INTO country (country_code, country) VALUES('WS', 'Samoa');
INSERT INTO country (country_code, country) VALUES('YE', 'Yemen');
INSERT INTO country (country_code, country) VALUES('YT', 'Mayotte');
INSERT INTO country (country_code, country) VALUES('ZA', 'South Africa');
INSERT INTO country (country_code, country) VALUES('ZM', 'Zambia');
INSERT INTO country (country_code, country) VALUES('ZW', 'Zimbabwe');

END;
