BEGIN NOT ATOMIC
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AG', 'Agrigento', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AL', 'Alessandria', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AN', 'Ancona', 'Marche');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AO', 'Aosta', 'Valle d''Aosta');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AQ', 'L''Aquila', 'Abruzzo');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AR', 'Arezzo', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AP', 'Ascoli-Piceno', 'Marche');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AT', 'Asti', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('AV', 'Avellino', 'Campania');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BA', 'Bari', 'Puglia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BT', 'Barletta-Andria-Trani', 'Puglia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BL', 'Belluno', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BN', 'Benevento', 'Campania');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BG', 'Bergamo', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BI', 'Biella', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BO', 'Bologna', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BZ', 'Bolzano', 'Trentino Alto Adige');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BS', 'Brescia', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('BR', 'Brindisi', 'Puglia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CA', 'Cagliari', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CL', 'Caltanissetta', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CB', 'Campobasso', 'Molise');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CI', 'Carbonia Iglesias', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CE', 'Caserta', 'Campania');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CT', 'Catania', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CZ', 'Catanzaro', 'Calabria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CH', 'Chieti', 'Abruzzo');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CO', 'Como', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CS', 'Cosenza', 'Calabria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CR', 'Cremona', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('KR', 'Crotone', 'Calabria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('CN', 'Cuneo', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('EN', 'Enna', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('FM', 'Fermo', 'Marche');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('FE', 'Ferrara', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('FI', 'Firenze', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('FG', 'Foggia', 'Puglia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('FC', 'Forli-Cesena', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('FR', 'Frosinone', 'Lazio');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('GE', 'Genova', 'Liguria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('GO', 'Gorizia', 'Friuli Venezia Giulia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('GR', 'Grosseto', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('IM', 'Imperia', 'Liguria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('IS', 'Isernia', 'Molise');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SP', 'La-Spezia', 'Liguria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('LT', 'Latina', 'Lazio');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('LE', 'Lecce', 'Puglia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('LC', 'Lecco', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('LI', 'Livorno', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('LO', 'Lodi', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('LU', 'Lucca', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MC', 'Macerata', 'Marche');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MN', 'Mantova', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MS', 'Massa-Carrara', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MT', 'Matera', 'Basilicata');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VS', 'Medio Campidano', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('ME', 'Messina', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MI', 'Milano', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MO', 'Modena', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('MB', 'Monza-Brianza', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('NA', 'Napoli', 'Campania');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('NO', 'Novara', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('NU', 'Nuoro', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('OG', 'Ogliastra', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('OT', 'Olbia Tempio', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('OR', 'Oristano', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PD', 'Padova', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PA', 'Palermo', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PR', 'Parma', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PV', 'Pavia', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PG', 'Perugia', 'Umbria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PU', 'Pesaro-Urbino', 'Marche');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PE', 'Pescara', 'Abruzzo');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PC', 'Piacenza', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PI', 'Pisa', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PT', 'Pistoia', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PN', 'Pordenone', 'Friuli Venezia Giulia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PZ', 'Potenza', 'Basilicata');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('PO', 'Prato', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RG', 'Ragusa', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RA', 'Ravenna', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RC', 'Reggio-Calabria', 'Calabria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RE', 'Reggio-Emilia', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RI', 'Rieti', 'Lazio');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RN', 'Rimini', 'Emilia Romagna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RM', 'Roma', 'Lazio');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('RO', 'Rovigo', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SA', 'Salerno', 'Campania');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SS', 'Sassari', 'Sardegna');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SV', 'Savona', 'Liguria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SI', 'Siena', 'Toscana');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SR', 'Siracusa', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('SO', 'Sondrio', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TA', 'Taranto', 'Puglia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TE', 'Teramo', 'Abruzzo');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TR', 'Terni', 'Umbria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TO', 'Torino', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TP', 'Trapani', 'Sicilia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TN', 'Trento', 'Trentino Alto Adige');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TV', 'Treviso', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('TS', 'Trieste', 'Friuli Venezia Giulia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('UD', 'Udine', 'Friuli Venezia Giulia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VA', 'Varese', 'Lombardia');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VE', 'Venezia', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VB', 'Verbania', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VC', 'Vercelli', 'Piemonte');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VR', 'Verona', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VV', 'Vibo-Valentia', 'Calabria');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VI', 'Vicenza', 'Veneto');
INSERT INTO country_other (country_other_code, country_other, country_other_desc) VALUES ('VT', 'Viterbo', 'Lazio');

END;
